query SearchPokemonSpecies($name: String!, $limit: Int!, $offset: Int!) {
    pokemon_v2_pokemonspecies(
        where: {name: {_ilike: $name}},
        limit: $limit,
        offset: $offset
    ) {
        id
        name
        capture_rate
        pokemon_v2_pokemoncolor {
            name
        }
        pokemon_v2_pokemons {
            id
            name
            pokemon_v2_pokemonabilities {
                pokemon_v2_ability {
                    name
                }
            }
        }
    }
}